### ISSUE TITLE
Упрощаем строку с аргументами конструктора

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#1]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L3

Эту строку можно упросить до `constructor({ username, name: { firstName, lastName }, password}) {`

**Comment by ribalko** [comment]
constructor({ username, name: { firstName, lastName }, password}) {
        this.username = username;
        this.name = {
            firstName,
            lastName
          };
        this.password = password;
    }
