### ISSUE TITLE
Вызов функции заменяем на умножение на текущий курс

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#10]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L86

```
const targetAmount = stocksInfo['EUR_NETCOIN'] * 500000;
```

Можно подумать как сделать эту строчку более универсальной.

**Comment by ribalko** [comment]
// переведем Евро в Неткоины  
                                const targetAmount = stocksInfo['EUR_NETCOIN'] * startCapital.amount;                                                        
                                Ivan.convertMoney({ fromCurrency: startCapital.currency, targetCurrency: 'NETCOIN', targetAmount: targetAmount }, (err, data) => {
...
