### ISSUE TITLE
Меняем цифру на конвертированную валюту

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#11]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L88

Тут и ниже меняем 500000 на targetAmount

**Comment by ribalko** [comment]
// переведем Евро в Неткоины  
                                const targetAmount = stocksInfo['EUR_NETCOIN'] * startCapital.amount;                                                        
                                Ivan.convertMoney({ fromCurrency: startCapital.currency, targetCurrency: 'NETCOIN', targetAmount: targetAmount }, (err, data) => {
...
