### ISSUE TITLE
Пишем объект в качестве значения

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#2]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L5

```
this.name = {
  firstName,
  lastName
};
```

**Comment by ribalko** [comment]
constructor({ username, name: { firstName, lastName }, password}) {
        this.username = username;
        this.name = {
            firstName,
            lastName
          };
        this.password = password;
    }
