### ISSUE TITLE
В качестве аргумента определяем только callback

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#3]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L9

`createUser(callback) {`

**Comment by ribalko** [comment]
createUser(callback) {
        return ApiConnector.createUser(
            {
              username: this.username,
              name: this.name,
              password: this.password
            },
            (err, data) => {
            console.log(`Creating user ${this.username}`);
            callback(err, data);
        });
    }
