### ISSUE TITLE
Всё аналогично createUser

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#5]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L16

**Comment by ribalko** [comment]
performLogin(callback) {
        return ApiConnector.performLogin(
            {
                username: this.username,
                password: this.password
            },
            (err, data) => {
            console.log(`Logging in user ${this.username}`);
            callback(err, data);
        });        
    }
