### ISSUE TITLE
Не тот метод вызывается

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#6]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L38

**Comment by ribalko** [comment]
transferMoney({ to, amount }, callback) {
        return ApiConnector.transferMoney({ to, amount }, (err, data) => {
            console.log(`Transfer ${amount} from ${this.username} to ${to}`);
            callback(err, data);
        });        
    }
