### ISSUE TITLE
Сначала вызываем getStocks, а внутри уже всё остальное

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#8]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L51

```
 getStocks((err, data) => {
        if (err) {
            console.error('Error during getting stocks');
        }
      // записываем текущее значение курсов валют
        const stocksInfo = data;
        const Ivan = new Profile({
      ...
```

**Comment by ribalko** [comment]
function main(){

    const Ivan = new Profile({
                    username: 'ivan',
                    name: { firstName: 'Ivan', lastName: 'Chernyshev' },
                    password: 'ivanspass',
                });

    const Petya = new Profile({
                   username: 'petya',
                   name: { firstName: 'Petr', lastName: 'Sergeev' },
                   password: 'petrspass',
                });                

    getStocks((err, data) => {
        if (err) {
            console.error('Error during getting stocks');
        }
        // записываем текущее значение курсов валют
        const stocksInfo = data;                

        // сначала создаем и авторизуем пользователя
        Ivan.createUser( (err, data) => {...
