### ISSUE TITLE
Изменились методы создания и авторизации

### ISSUE THREAD

**Issue by solarrust** [ribalko/bjs-diplom#9]
https://github.com/ribalko/bjs-diplom/blob/9f0840f0273dbf55fd59c49fbfbf9d22bc33b064/static/main.js#L65

Нужно поправить вызовы этих методов, убрать лишние аргументы

**Comment by ribalko** [comment]
// сначала создаем и авторизуем пользователя
        Ivan.createUser( (err, data) => {
            if (err) {
                console.error(`Error during creating ${Ivan.username}`);
            }
            else {
                console.log(`User ${Ivan.username} successfully created`);
                Ivan.performLogin( (err, data) => {
                    if (err) {
                        console.error(`Error during logging in ${Ivan.username}`);
                    }
                    else {
...
